// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDnDYoiv91Ca7ip414tdM5md_w8DRIbvA',
    appId: '1:873547403429:web:8bf2f5039cf4f33f533d4c',
    messagingSenderId: '873547403429',
    projectId: 'rentcar-3fc38',
    authDomain: 'rentcar-3fc38.firebaseapp.com',
    storageBucket: 'rentcar-3fc38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdqpZMuXU3EIpWW-ZuD2jtcY2enrBZPtM',
    appId: '1:873547403429:android:faf03b14ccc49803533d4c',
    messagingSenderId: '873547403429',
    projectId: 'rentcar-3fc38',
    storageBucket: 'rentcar-3fc38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF7OjFQ415xqUGpJnIXlQXU24bvDfCyYE',
    appId: '1:873547403429:ios:592be35c43ec0b08533d4c',
    messagingSenderId: '873547403429',
    projectId: 'rentcar-3fc38',
    storageBucket: 'rentcar-3fc38.appspot.com',
    iosBundleId: 'com.carrent.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF7OjFQ415xqUGpJnIXlQXU24bvDfCyYE',
    appId: '1:873547403429:ios:aac2e496f7aeb64c533d4c',
    messagingSenderId: '873547403429',
    projectId: 'rentcar-3fc38',
    storageBucket: 'rentcar-3fc38.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDnDYoiv91Ca7ip414tdM5md_w8DRIbvA',
    appId: '1:873547403429:web:dd9b4d82bb33973f533d4c',
    messagingSenderId: '873547403429',
    projectId: 'rentcar-3fc38',
    authDomain: 'rentcar-3fc38.firebaseapp.com',
    storageBucket: 'rentcar-3fc38.appspot.com',
  );

}